import NoncrossingMatching
/-! -/

#check NoncrossingMatching.uncrossing_shorter_of_cross
#check NoncrossingMatching.totalLength_swap_lt
#check NoncrossingMatching.exists_minimal_matching
#check NoncrossingMatching.exists_noncrossing_matching

#print axioms NoncrossingMatching.uncrossing_shorter_of_cross
#print axioms NoncrossingMatching.totalLength_swap_lt
#print axioms NoncrossingMatching.exists_noncrossing_matching
